#!/usr/bin/env bash
# Takes a subdomain and a domain and returns information about the subdomain

print_info () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_info "$2.$1" "$2"
else
    print_info "www.$1" "www"
    print_info "lb-01.$1" "54.89.59.86"
    print_info "web-01.$1" "54.164.246.16"
    print_info "web-02.$1" "100.25.45.215"
fi
